---
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "./"
    mode: 0644
    validate_certs: false

- name: Unarchive vector distrib
  ansible.builtin.unarchive:
    src: vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz
    dest: .
    remote_src: true

- name: Copy vector to /etc
  become: true
  ansible.builtin.copy:
    src: vector-x86_64-unknown-linux-musl
    dest: "{{ vector_install_directory }}"
    remote_src: true
    mode: 0644

- name: Create symlink for vector
  become: true
  ansible.builtin.file:
    src: "{{ vector_install_directory }}/vector-x86_64-unknown-linux-musl/bin/vector"
    path: "/usr/bin/vector"
    state: link

- name: Create vector config
  become: true
  ansible.builtin.template:
    src: vector_config.j2
    dest: "{{ vector_install_directory }}/vector-x86_64-unknown-linux-musl/config/config.yaml"
    mode: 0644

- name: Create systemd config
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: "/etc/systemd/system/vector.service"
    mode: 0644
  notify: Start vector service
...
