---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/centos/centos:centos7
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
#    capabilities:
#      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      container: podman
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - destroy