---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: install python3 and pip
    become: true
    ansible.builtin.apt:
      name:
        - python3
        - python3-pip

  - name: install yamllint
    ansible.builtin.shell: pip3 install yamllint

  - name: check vector config
    ansible.builtin.shell: "yamllint /etc/vector-x86_64-unknown-linux-musl/config/config.yaml"
    register: check_vector_config

  - name: check RC for checking config
    ansible.builtin.assert:
      that: check_vector_config.rc == 0
      success_msg: "Vector config is valid"

  - name: check vector service status
    ansible.builtin.shell: "systemctl status vector"
    register: check_vector_service_status

  - name: check RC for checking service status
    ansible.builtin.assert:
      that: check_vector_service_status.rc == 0
      success_msg: "Vector service is running"
